name: Pylint

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Silleellie/pylint-github-action@v2.1
    - name: Install dependencies
      run: pip3 install -r requirements.txt
      with:
        lint-path: utils.py
        python-version: 3.11
